apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-cross
  labels:
    app: teste-cross
    component: web
spec:
  selector:
    matchLabels:
      app: teste-cross
      component: web
  template:
    metadata:
      labels:
        app: teste-cross
        component: web
    spec:
      containers:
      - name: teste-cross
        image: diegoluisi/teste-cross:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi